In [1]:
!pip install numpy

In [9]:
import numpy as np
import pandas as pd

height = [170, 160, 150, 140, 180, 200]

minHeight = np.min(height)
print(minHeight)

maxHeight = np.max(height)
print(maxHeight)

meanHeight = np.mean(height) #np.average(height)
print(meanHeight)

stdHeight = np.std(height) #표준편차
print(stdHeight)

sumHeight = np.sum(height)
print(sumHeight)

140
200
166.66666666666666
19.72026594366539
1000


In [10]:
from google.colab import files

f = files.upload()

Saving gni.xlsx to gni.xlsx


In [34]:
import numpy as np
from google.colab import files
import openpyxl

wb = openpyxl.load_workbook('gni.xlsx')
print(wb.sheetnames)
load_ws = wb['Sheet0']

gni = []
cnt = 0
for row in load_ws.rows:
    if cnt == 0:
        cnt += 1
        continue
    row_value = []
    for cell in row:
        row_value.append(cell.value)
    gni.append(float(row_value[1].replace(',', "")))
    print(row_value)
print(gni)

print(np.min(gni))
print(np.max(gni))
print(np.average(gni))
print(np.std(gni))
print(np.sum(gni))

gni.sort()
print(gni)
gni.sort(reverse=True)
print(gni)

wb.close()

['Sheet0']
['2014', '3,094.8']
['2015', '3,260.2']
['2016', '3,411.2']
['2017', '3,588.6']
['2018', '3,693.0']
['2019', '3,753.9']
['2020', '3,776.6']
['2021', '4,065.4']
['2022p', '4,248.7']
['2023p', '4,405.1']
[3094.8, 3260.2, 3411.2, 3588.6, 3693.0, 3753.9, 3776.6, 4065.4, 4248.7, 4405.1]
3094.8
4405.1
3729.749999999999
398.4008640803883
37297.49999999999
[3094.8, 3260.2, 3411.2, 3588.6, 3693.0, 3753.9, 3776.6, 4065.4, 4248.7, 4405.1]
[4405.1, 4248.7, 4065.4, 3776.6, 3753.9, 3693.0, 3588.6, 3411.2, 3260.2, 3094.8]


In [31]:
gniSorted = gni.sort()
print(gniSorted)

None


In [57]:
import numpy as np
import pandas as pd

#6.1 배열 생성
#리스트를 생성하고 배열로 변환하기
list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape: ', a.shape)
print('a[0]: ', a[0])
#2차원 배열 생성하기
b = np.array([[1, 2, 3], [4, 5, 6]])
print('b.shape: ', b.shape)
print('b[0,0]: ', b[0,0])
print('b[0]: ', b[0])

#6.2 배열생성 함수
a = np.zeros(2)
print('a\n', a)
b = np.zeros((2, 2))
print('b\n', b)
c = np.ones((2, 3))
print('c\n', c)
d = np.full((2, 3), 5)
print('d\n', d)
e = np.eye(3)
print('e\n', e)

#6.3
#실수형 배열 생성하기
a = np.array([1, 2], dtype = np.float64)
print(a.dtype)
#정수형 배열로 변환하기
a_i8 = a.astype(np.int8)
print(a_i8.dtype)

#6.4 배열의 속성 호출
arr = np.array([[0, 1, 2], [3, 4, 5]])

print('type(arr):', type(arr)) #어레이타입
print('arr.ndim:', arr.ndim)  #차원
print('arr.dtype:', arr.dtype) #데이터타입
print('arr.itemsize:', arr.itemsize) #아이템사이즈
print('arr.size:', arr.size) #사이즈
print('arr.nbytes:', arr.nbytes) #바이트
print('arr.T:\n', arr.T)       #
print('arr.shape:', arr.shape)#모양

#6.5 배열 모양 변경
#1차원 배열 생성하기
a = np.arange(8)
print('a\n', a)

#다차원 배열로 변경하기
a.shape = (2, 4)
print('shape\n', a)

#1차원 배열로 변경하기
print('flatten\n', a.flatten())

#resize 함수로 모양 변경하기
a.resize((4, 2))
print('resize\n', a)

#6.6 행렬의 행과 열 교차
a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)

b = a.transpose()
print('b\n', b)
c = a.T
print('c\n', c)

#6.7 배열로 마스킹
mask = np.array([0, 1 ,1, 0], dtype = bool)
print(mask)

data = np.random.randn(4, 2)
print('\ndata 출력\n', data) #랜덤 데이터 배열 data는 책과 다르게 나타남

print('\n마스킹된 데이터 출력\n', data[mask])
print('\n마스킹 역전된 데이터 출력\n', data[~mask])

#6.8 조건식으로 마스킹
posit = data[data > 0]
print('양수 데이터 출력', '\n', posit)

#다중 조건
over1 = data[1][data[1] > 0]
print('두 번째 행의 양수 데이터 출력', '\n', over1)

#6.9 얕은 복사
a = np.arange(6)
b = a
print(a)
print(b is a)

b[0] = 10   #b를 바꾸었는데
print(a)    #a가 바뀐다

#6.10 깊은 복사
a = np.arange(6)
c = a.copy()

c[0] = 20
print('A: ', a)
print('C: ', c)

#6.11
a = np.array([3, 2, 5, 1, 4])
print('원본\n', a)
print('정렬 후\n',np.sort(a)) #np.sort(a) 는 원본 순서가 유지
print('원본\n', a)
print('정렬한 인덱스\n', np.argsort(a))
a.sort( )                   #a.sort()는 원본을 정렬
print('원본\n', a)

a.shape:  (4,)
a[0]:  1
b.shape:  (2, 3)
b[0,0]:  1
b[0]:  [1 2 3]
a
 [0. 0.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64
int8
type(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48
arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)
a
 [0 1 2 3 4 5 6 7]
shape
 [[0 1 2 3]
 [4 5 6 7]]
flatten
 [0 1 2 3 4 5 6 7]
resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
a
 [[0 1 2]
 [3 4 5]]
b
 [[0 3]
 [1 4]
 [2 5]]
c
 [[0 3]
 [1 4]
 [2 5]]
[False  True  True False]

data 출력
 [[-0.03296949 -0.26205925]
 [-0.20735999 -1.03681475]
 [ 1.19976954 -0.5009998 ]
 [-1.60661454 -1.08106221]]

마스킹된 데이터 출력
 [[-0.20735999 -1.03681475]
 [ 1.19976954 -0.5009998 ]]

마스킹 역전된 데이터 출력
 [[-0.03296949 -0.26205925]
 [-1.60661454 -1.08106221]]
양수 데이터 출력 
 [1.19976954]
두 번째 행의 양수 데이터 출력 
 []
[0 1 2 3 4 5]
True
[10  1  2  3  4  5]
A:  [0 1 2 3 4 5]
C:  [20  1  2  3  4  5]
원본
 [3 2 5 1 4]
정렬 후
 [1 2 3 4 5]
원본
 [3